services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: agent_platform
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: agent_pass_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_pass_2025
      MONGO_INITDB_DATABASE: agent_memory
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d

  neo4j:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: neo4j/neo4j_pass_2025
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./init-neo4j:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  mongo_data:
  neo4j_data:
